// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcND7Zy2Q2QUCgQ4EMtmhvjAUoT7GDDDA',
    appId: '1:317295058676:web:25203e8cdb237f5d4488a1',
    messagingSenderId: '317295058676',
    projectId: 'firstapp-5e731',
    authDomain: 'firstapp-5e731.firebaseapp.com',
    storageBucket: 'firstapp-5e731.appspot.com',
    measurementId: 'G-5WVPMSM85W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9pXCxNmYK_taAmxJ5NAP1NOYX3yE-TtI',
    appId: '1:317295058676:android:2afa24cd1aac19b64488a1',
    messagingSenderId: '317295058676',
    projectId: 'firstapp-5e731',
    storageBucket: 'firstapp-5e731.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrEaVBq36at8T_I9ivmh9obu8QflAea3A',
    appId: '1:317295058676:ios:e81fb78ef40057844488a1',
    messagingSenderId: '317295058676',
    projectId: 'firstapp-5e731',
    storageBucket: 'firstapp-5e731.appspot.com',
    iosClientId: '317295058676-3us3gma9cbudqdq669v7rgrq2648d4op.apps.googleusercontent.com',
    iosBundleId: 'com.example.firstapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrEaVBq36at8T_I9ivmh9obu8QflAea3A',
    appId: '1:317295058676:ios:e81fb78ef40057844488a1',
    messagingSenderId: '317295058676',
    projectId: 'firstapp-5e731',
    storageBucket: 'firstapp-5e731.appspot.com',
    iosClientId: '317295058676-3us3gma9cbudqdq669v7rgrq2648d4op.apps.googleusercontent.com',
    iosBundleId: 'com.example.firstapp',
  );
}
